### ISSUE TITLE
NMAP Scanner fails without any failure feedback

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/scanner-infrastructure-nmap#4]
While Running a NMAP process with multiple targets the scanner fails with (log):
```
Started working on Job "20eb4e41-6a5b-11e8-810c-0a580a8201fd"
--
  | SCANNING 6 locations
  | SCANNING location: ***********, parameters:
  | SCANNING location: ***********, parameters:
  | SCANNING location: ***********, parameters:
  | Failed to resolve "**************".
  | WARNING: No targets were specified, so 0 hosts scanned.
  | Failed to perform Job "20eb4e41-6a5b-11e8-810c-0a580a8201fd" Error: Failed to execute nmap portscan.
  | at ScannerScaffolding.worker [as _worker] (/src/src/nmap.js:81:19)
  | at <anonymous>
  | at process._tickCallback (internal/process/next_tick.js:188:7)
```

But the engine process is still running. So...
- the failure feedback is somehow missing (API -> Failure)
- The scanner shouldn't stop to scan all other (configured) hosts

**Comment by rseedorff** [comment]
I think the problem occurs because one of the hostnames in the target list was not reachable for the scanner. It would be nice if this results in a finding: "Failed to resolve" instead of an error...

**Comment by J12934** [comment]
Ok this should be fixed now.
Unfortunalty the fix is quite ugly at the moment because nmap or node-nmap is inconsistent in its error messages. On some occasions it fails because the hostname could not be resolved, but fails with an empty error message. When this happens we now assume that this was because of the unresolvable domain name but I'm not sure if this empty message might not happen for other nmap errors as well. 

So if see `Failed to resolve "hostname".` finding which should not be there please report this as this would be an indication that the fix conflicts with other errors.
